export const CROSSWORDS_SET_FAVORITES = 'CROSSWORDS_SET_FAVORITES';
export const CROSSWORDS_ADD_FAVORITE_ID = 'CROSSWORDS_ADD_FAVORITE_ID';
export const CROSSWORDS_REMOVE_FAVORITE_ID = 'CROSSWORDS_REMOVE_FAVORITE_ID';